# ===================================================================
# BOLT Platform: BERT 任务配置文件
# ===================================================================

# --- 必需参数 (通常由 sh 脚本覆盖) ---
dataset: "banking"
known_cls_ratio: 0.5

# --- 常用参数 ---
seed: 0
gpu_id: "4" # 根据您的原始脚本设置
data_dir: "data"
output_dir: "outputs/gcd/bert"
bert_model: "./pretrained_models/bert-base-uncased"
backbone: "bert"

# --- 数据集与标签设置 ---
fold_num: 5
fold_idx: 0

# --- 训练参数 ---
n_epochs: 10
lr: !!float 0.001
train_batch_size: 16
eval_batch_size: 128
max_seq_length: 55 # banking 数据集的建议值