# ===================================================================
# BOLT Platform: DeepAligned 算法配置文件 (v2)
# ===================================================================

# --- 必需参数 ---
dataset: "banking"
known_cls_ratio: 0.75

# --- 常用参数 ---
seed: 0
gpu_id: "3"
data_dir: "data"
save_results_path: "outputs/gcd/deepaligned/results"
pretrain_dir: "outputs/gcd/deepaligned/premodels"
bert_model: "./pretrained_models/bert-base-uncased"

# --- 数据集与标签设置 ---
labeled_ratio: 0.1
fold_num: 5
fold_idx: 0

# --- 训练参数 ---
train_batch_size: 128
eval_batch_size: 64
num_pretrain_epochs: 1
num_train_epochs: 1
lr_pre: !!float 5e-5
lr: !!float 5e-5
warmup_proportion: 0.1
wait_patient: 20

# --- 算法专属参数 ---
method: "DeepAligned"
cluster_num_factor: 1.0
feat_dim: 768

# --- 【新增】数据集专属配置 ---
dataset_specific_configs:
  clinc:
    max_seq_length: 30
  stackoverflow:
    max_seq_length: 45
  banking:
    max_seq_length: 55
  hwu:
    max_seq_length: 55