# ===================================================================
# BOLT Platform: DPN 算法配置文件 (v2)
# ===================================================================

# --- 必需参数 ---
dataset: "banking"
known_cls_ratio: 0.75

# --- 常用参数 ---
seed: 0
data_dir: "data"
save_results_path: "outputs/gcd/dpn/results"
pretrain_dir: "outputs/gcd/dpn/premodels"
bert_model: "./pretrained_models/bert-base-uncased"
labeled_ratio: 0.1
fold_num: 5
fold_idx: 0

# --- 训练参数 ---
pretrain_batch_size: 32
train_batch_size: 256
eval_batch_size: 64
num_pretrain_epochs: 1
num_train_epochs: 1
lr_pre: !!float 5e-5
lr: !!float 1e-5
warmup_proportion: 0.1
wait_patient: 20

# --- 算法专属参数 ---
method: "DPN"
cluster_num_factor: 1.0
feat_dim: 768
momentum_factor: 0.9
temperature: 0.07

# --- 【新增】数据集专属配置 ---
dataset_specific_configs:
  clinc:
    max_seq_length: 30
    gamma: 10
    num_train_epochs: 80
  stackoverflow:
    max_seq_length: 45
    gamma: 90
    num_train_epochs: 10
  banking:
    max_seq_length: 55
    gamma: 10
    num_train_epochs: 60
  mcid:
    max_seq_length: 65
    gamma: 30
    num_train_epochs: 80
  ecdt:
    max_seq_length: 65
    gamma: 30
    num_train_epochs: 80
  hwu:
    max_seq_length: 20
    gamma: 30
    num_train_epochs: 80