# ===================================================================
# BOLT Platform: GeoID 算法配置文件 (v2)
# ===================================================================

# --- 必需参数 ---
dataset: "banking"
known_cls_ratio: 0.25

# --- 常用参数 ---
seed: 0
data_dir: "data"
save_results_path: "outputs/gcd/geoid"
save_model_path: "outputs/gcd/geoid/models"
bert_model: "./pretrained_models/bert-base-uncased"
tokenizer: "./pretrained_models/bert-base-uncased"
labeled_ratio: 0.1
fold_num: 5
fold_idx: 0

# --- 训练参数 ---
pretrain_batch_size: 100
train_batch_size: 128
eval_batch_size: 128
num_pretrain_epochs: 50
num_train_epochs: 100
num_warm_epochs: 20
lr_pre: !!float 5e-5
lr: !!float 1e-3
warmup_proportion: 0.2
wait_patient: 20
grad_clip: 1.0
es_metric: "ACC"        # 或 "NMI" | "ARI" | "H-Score"（若你扩展了返回）
es_patience: 10
es_min_delta: 0.0

# --- 算法专属参数 ---
method: "CLNN" 
cluster_num_factor: 1.0
cluster_temperature: 1.0
feat_dim: 128
rtr_prob: 0.25
lambda_v: 3.0
temp: 0.07
view_strategy: "rtr"
update_per_epoch: 5
topk: 64

# --- 【新增】数据集专属配置 ---
dataset_specific_configs:
  hwu:
    max_seq_length: 55
  clinc:
    max_seq_length: 30
  banking:
    max_seq_length: 55
  stackoverflow:
    max_seq_length: 45
  mcid:
    max_seq_length: 55
  ecdt:
    max_seq_length: 55
  # --- Medium Length / Paragraph Datasets ---
  stackoverflow:
    max_seq_length: 45 # Although a large dataset, individual posts for classification are often concise.
  AGNews:
    max_seq_length: 128
  Yahoo: # Yahoo Answers
    max_seq_length: 128
  ele:
    max_seq_length: 200
  DBPedia:
    max_seq_length: 256
  medical:
    max_seq_length: 256

  # --- Long Document Datasets ---
  news:
    max_seq_length: 500
  thucnews:
    max_seq_length: 500
  20NG: # 20 Newsgroups
    max_seq_length: 512
  X-Topic:
    max_seq_length: 512