# ===================================================================
# BOLT Platform: Glean 算法配置文件 (v2)
# ===================================================================

# --- 必需参数 ---
dataset: "banking"
known_cls_ratio: 0.25

# --- 常用参数 ---
seed: 42
gpu_id: "0"
data_dir: "data"
save_results_path: "results/gcd/glean"
save_model_path: "outputs/gcd/glean/models"
pretrain_dir: "outputs/gcd/glean/premodels"
bert_model: "./pretrained_models/bert-base-uncased"
tokenizer: "./pretrained_models/bert-base-uncased"
experiment_name: "deepseek-v3:671b"
running_method: "GCDLLMs"

# --- 训练与流程控制 ---
num_pretrain_epochs: 100
num_train_epochs: 100
lr_pre: !!float 5e-5
lr: !!float 1e-5
pretrain_batch_size: 48
train_batch_size: 48
eval_batch_size: 64
warmup_proportion: 0.1
wait_patient: 20
grad_clip: 1.0
es_metric: "Acc"        # 可选: Acc | NMI | ARI | H-Score
es_patience: 5          # 连续 5 个 epoch 无显著提升就停
es_min_delta: 0.5       # 至少提升 0.2 才算“更好”

# --- 数据集与标签设置 ---
label_setting: "ratio"
labeled_ratio: 0.1
labeled_shot: 10
fold_num: 5
fold_idx: 0

# --- Glean 核心算法参数 ---
architecture: "Loop"
# topk 从这里移到下面的专属配置中
temp: 0.07
view_strategy: "rtr"
update_per_epoch: 5

# --- DistillLoss 相关参数 ---
memax_weight: 1.0
warmup_teacher_temp: 0.07
teacher_temp: 0.04
warmup_teacher_temp_epochs: 5
ce_weight: 1.0
cl_weight: 1.0
sup_weight: 1.0
weight_ce_unsup: 0.0
weight_cluster_instance_cl: 0.0

# --- LLM 与 Prompt 相关参数 ---
api_key: "6c5c96209c4ef126a87fbe9840fab7c346b4c6fb6a57529fce7dea01c683fd1b" # 建议从环境变量或安全方式读取
api_base: "https://uni-api.cstcloud.cn/v1"
llm: "deepseek-v3:671b"
query_samples: 500
options: 5
interpret_sampling_strategy: "nearest_center"
interpret_num_representatives: 10
sampling_strategy: "highest"
allocation_degree: 1.0
options_cluster_instance_ratio: 0.5
known_demo_num_per_class: 5
known_demo_num_per_class_c: 2
filter_threshold: 0.8
filter_threshold_c: 0.85

# --- 消融实验参数 ---
prompt_ablation: "full"
component_ablation: "full"

# --- 【新增】数据集专属配置 ---
dataset_specific_configs:
  # --- 任务类型: "intent" (意图分类) ---
  clinc:
    max_seq_length: 30
    topk: 50
    task: "intent"
  stackoverflow:
    max_seq_length: 45
    topk: 500
    task: "intent"
  banking:
    max_seq_length: 55
    topk: 50
    task: "intent"
  hwu:
    max_seq_length: 55
    topk: 55
    task: "intent"
  mcid:
    max_seq_length: 55
    topk: 55
    task: "intent"
  ecdt:
    max_seq_length: 55
    topk: 55
    task: "intent"

  # --- 任务类型: "question" (问题分类) ---
  TREC:
    max_seq_length: 40
    topk: 50
    task: "question"
  Yahoo: # Yahoo Answers
    max_seq_length: 128
    topk: 200
    task: "question"
  
  # --- 任务类型: "topic" (主题分类) ---
  AGNews:
    max_seq_length: 128
    topk: 200
    task: "topic"
  DBPedia:
    max_seq_length: 256
    topk: 200
    task: "topic"
  medical:
    max_seq_length: 256
    topk: 200
    task: "topic"
  ele:
    max_seq_length: 200
    topk: 500
    task: "topic"
  news:
    max_seq_length: 500
    topk: 500
    task: "topic"
  thucnews:
    max_seq_length: 500
    topk: 500
    task: "topic"
  20NG: # 20 Newsgroups
    max_seq_length: 512
    topk: 500
    task: "topic"
  X-Topic:
    max_seq_length: 512
    topk: 500
    task: "topic"