# TAN 方法的配置模板 
# ----------------------------------

# --- 基础设置 ---
seed: 0
gpu_id: "0"

# --- 路径设置 ---
data_dir: "./data"
bert_model: "./pretrained_models/bert-base-uncased"
output_dir: "./outputs/gcd/tan"
pretrain_dir: "./outputs/gcd/tan/premodels" 

# --- 数据与任务设置 ---
dataset: "banking"
known_cls_ratio: 0.75
labeled_ratio: 0.1
fold_num: 5
# fold_idx: 0

# --- 模型设置 ---
feat_dim: 768

# --- 训练设置 ---
num_train_epochs: 2
train_batch_size: 256
eval_batch_size: 64
lr: 1e-5
warmup_proportion: 0.1
wait_patient: 20

# --- TAN 专属超参数 ---
beta: 100
topk: 5.0
alpha: 0.8
temperature: 0.07
cluster_num_factor: 1.0

# --- 预训练设置 ---
num_pretrain_epochs: 100
pretrain_batch_size: 32
lr_pre: 1e-5

# --- 数据集专属配置 ---
dataset_specific_configs:
  clinc:
    max_seq_length: 30
    num_train_epochs: 20
  stackoverflow:
    max_seq_length: 45
    num_train_epochs: 10
  banking:
    max_seq_length: 55
    num_train_epochs: 2
  hwu:
    max_seq_length: 55
    num_train_epochs: 20
  mcid:
    max_seq_length: 55
    num_train_epochs: 20
  ecdt:
    max_seq_length: 55
    num_train_epochs: 20