# ===================================================================
# BOLT Platform: Traditional Methods 配置文件 (v2)
# ===================================================================

# --- 必需参数 ---
dataset: "banking"
known_cls_ratio: 0.75
method: "DeepAligned"

# --- 常用参数 ---
seed: 0
gpu_id: "0"
data_dir: "data"
save_results_path: "outputs/gcd/traditional_methods"
pretrain_dir: "outputs/gcd/traditional_methods/premodels"
bert_model: "./pretrained_models/bert-base-uncased"
labeled_ratio: 1.0
fold_num: 5
fold_idx: 0

# --- 训练参数 ---
train_batch_size: 128
eval_batch_size: 64
num_pretrain_epochs: 3
wait_patient: 20
lr: !!float 5e-5
lr_pre: !!float 5e-5
warmup_proportion: 0.1

# --- 算法专属参数 ---
cluster_num_factor: 1.0
feat_dim: 768

# --- 数据集专属配置 ---
dataset_specific_configs:
  clinc:
    max_seq_length: 30
  banking:
    max_seq_length: 55
  hwu:
    max_seq_length: 55
  stackoverflow:
    max_seq_length: 55
  ele:
    max_seq_length: 200
  news:
    max_seq_length: 500
  mcid:
    max_seq_length: 50
  thucnews:
    max_seq_length: 500

# --- 开关型参数 (在 sh 脚本中直接添加) ---
# freeze_bert_parameters: true
# save_model: true
# pretrain: true