# 任务 -> 方法映射（可按需增删）
maps:
  gcd: [alup, deepaligned, dpn, geoid, glean, loop, plm_gcd, sdc, tan]
  openset: [ab, adb, clap, deepunk, doc, dyen, knncon, plm_ood, scl]

# 若仅跑子集，可指定 methods（会从 maps 里筛选）
# methods: [tan,alup, dpn, sdc, ab, clap]
methods: [tan]

# 数据集（留空则自动在 data/ 与 data/<task>/ 下尝试发现）
datasets: [banking]


# 网格搜索参数
grid:
  known_cls_ratio: [0.25]
  labeled_ratio: [0.1]
  fold_idxs: [0]
  seeds: [0]
  cluster_num_factor: [1.0]   # 需要多值就加上 [0.8, 1.0, 1.2]
  # num_train_epochs: [1]

# 运行参数
run:
  gpus: [0]      # 留空则不设置 CUDA_VISIBLE_DEVICES
  max_workers: 1    # 并行线程数
  num_pretrain_epochs: 1
  num_train_epochs: 1


# 路径（可选）
paths:
  results_dir: results/task         # 汇总与去重索引的根目录
  logs_dir: logs                    # 单次运行日志

# 单方法脚本/结果路径覆盖（可选；默认 scripts/{task}/{method}.sh 和 outputs/{task}/{method}/**/results.csv）
scripts_override:
  # sdc: scripts/custom/sdc_entry.sh

result_globs_override:
  # ab: outputs/openset/ab/**/final_results.csv

# 注入到每次运行的公共额外参数（进入 args JSON，子脚本可解析）
extra_args:
  data_dir: ./data
  fold_num: 5
  gpu_id: 0            # 仅示意；真正的 GPU 绑定由 CUDA_VISIBLE_DEVICES 控制

# 按方法分别追加/覆盖 extra_args（可选）
per_method_extra:
  alup:
    num_train_epochs: 1
    pretrain_batch_size: 16
    train_batch_size: 32
  dpn:
    temperature: 0.1