# CLAP 方法 - 阶段一 Finetune 的配置文件
# ----------------------------------

# --- 基础设置 ---
seed: 0
gpu_id: "0"

# --- 数据与任务设置 ---
dataset: "banking"
data_dir: "./data"
known_cls_ratio: 0.25
labeled_ratio: 1.0
fold_idx: 0
fold_num: 5
max_seq_length: 128

# --- 模型与训练设置 (根据 finetune/init_parameter.py) ---
bert_base_model: "./pretrained_models/bert-base-uncased"
freeze_bert_parameters: false
pretrain_lr: 2e-5
train_batch_size: 32
eval_batch_size: 32
num_pretrain_epochs: 10.0
kccl_k: 5
temperature: 1.0
KCCL_LOSS_LAMBDA: 0.25
CE_LOSS_LAMBDA: 0.75
metric_type: 1 

# --- 新增：补全所有缺失的参数 ---
warmup_proportion: 0.1
pretrain_loss_type: 1 
optimizer_lr: 1 
seed_data: 0
neg_num: 1
neg_method: 0
kccl_euc: 0
ks: 1
km: 0
# --- 输出目录设置 ---
# 注意：这里我们只定义一个总的输出目录
# 具体的子目录（如 finetuned_model）我们将在代码中基于此路径创建
output_dir: "./outputs/openset/clap"