# CLAP 方法 - 阶段二 Boundary Adjustment 的配置文件
# ----------------------------------

# --- 基础设置 ---
seed: 0
gpu_id: "0"

# --- 数据与任务设置 ---
dataset: "banking"
data_dir: "./data"
known_cls_ratio: 0.25
labeled_ratio: 1.0
fold_idx: 0
fold_num: 5

# --- 模型与训练设置 (根据 boundary_adjustment/init_parameter.py) ---
# 关键：这里需要加载第一阶段训练好的模型
pretrain_dir: "./outputs/openset/clap/finetuned_model" # 这个路径指向第一阶段的输出
max_seq_length: 128

# 训练超参数
lr_boundary: 0.05
num_train_epochs: 100.0
train_batch_size: 64
eval_batch_size: 256
wait_patient: 10

# 模型与损失函数特定参数
feat_dim: 768
p: 0
n: 0 # 负样本数
cosine: true
neg_from_gen: false

# --- 输出目录设置 ---
output_dir: "./outputs/openset/clap"