# CLAP 方法 - 统一配置文件
# ----------------------------------

# --- 基础设置 (两阶段通用) ---
seed: 0
gpu_id: "0"

# --- 数据与任务设置 (两阶段通用) ---
dataset: "banking"
data_dir: "./data"
known_cls_ratio: 0.25
labeled_ratio: 1.0
fold_idx: 0
fold_num: 5
max_seq_length: 128

# --- 输出目录设置 (两阶段通用) ---
# 这是一个顶层目录，具体的子目录由脚本自动生成
output_dir: "./outputs/openset/clap"

# ==========================================================
# --- 阶段一：Finetune (run_kccl.py) 专属参数 ---
# ==========================================================
finetune:
  bert_base_model: "./pretrained_models/bert-base-uncased"
  freeze_bert_parameters: false
  pretrain_lr: !!float 2e-5
  train_batch_size: 32
  eval_batch_size: 32
  num_pretrain_epochs: 10.0
  kccl_k: 5
  temperature: 1.0
  KCCL_LOSS_LAMBDA: 0.25
  CE_LOSS_LAMBDA: 0.75
  metric_type: 1
  warmup_proportion: 0.1
  pretrain_loss_type: 1
  optimizer_lr: 1
  seed_data: 0
  neg_num: 1
  neg_method: 0
  kccl_euc: 0
  ks: 1
  km: 0

# ==========================================================
# --- 阶段二：Boundary Adjustment (run_adbes.py) 专属参数 ---
# ==========================================================
boundary_adjustment:
  # 注意：pretrain_dir 会被 .sh 脚本动态覆盖，这里的值仅作参考
  # pretrain_dir: "./outputs/openset/clap/finetuned_model" 
  lr_boundary: 0.05
  num_train_epochs: 1.0
  train_batch_size: 64
  eval_batch_size: 256
  wait_patient: 10
  feat_dim: 768
  p: 0
  n: 0
  cosine: true
  neg_from_gen: false
