# DeepUnk 方法的通用配置模板
# ----------------------------------

# --- 基础设置 ---
seed: 0
gpu_id: "0"

# --- 数据与任务设置 ---
dataset: "banking"
data_dir: "./data"
known_cls_ratio: 0.25
labeled_ratio: 0.1
fold_idx: 0
fold_num: 5

# --- 模型与训练设置 ---
# 路径设置
embedding_file: "./pretrained_models/glove.6B.300d.txt"

# 训练超参数
n_epochs: 8
learning_rate: 0.001   # 对应原脚本的 lr
train_batch_size: 16   # 对应原脚本的 batch_size

# --- 输出目录设置 ---
output_dir: "./outputs/openset/deepunk"